### ISSUE TITLE
I cant get it to work

### ISSUE THREAD

**Issue by soovui** [pkarun/Blynk-PZEM-004T-v3.0-Multiple-device#1]
1st Issue: 
Not able to compile
error: SimpleTimer.h: No such file or directory

2nd Issue:
I comment out the SimpleTimer.h and successfully compiled but I am not able to read anything.  Is that necessarily to uncomment SimpleTimer.h? 

I am using Arduino 1.8.10.  

====================================================
Now checking Modbus 1
Failed to read modbus 1
====================================================
Now checking Modbus 2
Failed to read modbus 2

Not able to read anything from the D5 and D6.  I tried other pin D1 D2 and TX RX also cannot.  Tried to swap to a new ESP8266, still remain the same.  I tried example given PZEM

**Comment by pkarun** [comment]
1st issue:

I guess you might be missing the library. Please check and install all the required libraries.

2nd issue:

Don't disable anything. Install all the required libraries and compile them. 

To get the output you need to assign an address to each pzem device first or else it won't work. Please read the document and follow it or google it.

I guess your ESP is fine. Your setup is not right. 

There is no issues with the code. You need a proper setup before you use the code or else it won't work.
