### ISSUE TITLE
Half reading 32 bit register 

### ISSUE THREAD

**Issue by sandroxGH** [pkarun/Blynk-PZEM-004T-v3.0-Multiple-device#2]
The current power and energy have 32 bit register with  "nodeX.getResponseBuffer(0xXX)" can read only 16 bit is correct?
I think it looking the energy counter some time restart from 0 after have count 66.

**Comment by Renato-REDS** [comment]
Olá @sandroxGH,

você está certo, eu também tive o mesmo problema. 
Para você ter a leitura completa dos valores de potência, energia e corrente em 16 bits, troque as linhas:

current_usage_1      = (node2.getResponseBuffer(0x01) / 1000.000f);
active_power_1       = (node2.getResponseBuffer(0x03) / 10.0f);
active_energy_1      = (node2.getResponseBuffer(0x05) / 1000.0);

para:
current_usage_2      = (node2.getResponseBuffer(0x01) | (node1.getResponseBuffer(0x02)) << 16) / 1000.000f;
active_power_2       = (node2.getResponseBuffer(0x03) | (node1.getResponseBuffer(0x04)) << 16) / 10.0f;
active_energy_2      = (node2.getResponseBuffer(0x05) | (node1.getResponseBuffer(0x06)) << 16) / 1000.0f;

assim quando os valores forem maiores, você irá conseguir ler sem problema. (sem o falso 0).

Espero ter ajudado.

**Comment by sandroxGH** [comment]
Sí, lo resolví a tu manera.
Gracias por el apoyo, espero que también ayude a otros.


Il giorno lun 27 lug 2020 alle ore 20:39 Renato-REDS <
notifications@github.com> ha scritto:
